modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory
license="MIT"

[[mods]] #mandatory
modId="freelook" #mandatory
version="${version}" #mandatory
displayName="FreeLook" #mandatory
description='''FPS Style FreeLook!''' #mandatory
authors="jmilthedude" #optional


[[dependencies.freelook]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.freelook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"