modLoader="javafml" #mandatory
loaderVersion="[49,)" #mandatory
license="MIT"

[[mods]] #mandatory
modId="freelook" #mandatory
version="1.20.4" #mandatory
displayName="FreeLook" #mandatory
description='''FPS Style FreeLook!''' #mandatory
authors="jmilthedude" #optional


[[dependencies.freelook]]
    modId="forge"
    mandatory=true
    versionRange="[49,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.freelook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"